version : '3.8'
services:
 webapp:
  image: dockertomcat9openjdk17mywebapp:latest
  ports:
   - "8089:8080"
  deploy:
   replicas: 1
 db:
  image: mysql:latest
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD : root
  deploy:
   replicas: 1
